"""Added photo to Profile table

Revision ID: 4f8627c0f5a8
Revises: 3a10a121a11a
Create Date: 2025-04-29 01:51:27.359478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8627c0f5a8'
down_revision = '3a10a121a11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
